name: Auto Build DEV
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    environment: KeywordGacha

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Update Python
        run: |
          python -m pip install --upgrade pip

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --name KeywordGacha --clean --noconfirm --onefile main.py

      - name: Compress Archive
        run: |
          # 复制文件到dist目录
          Copy-Item -Path "prompt" -Destination "dist\" -Recurse -Force
          Copy-Item -Path "config.json" -Destination "dist\" -Force
          Copy-Item -Path "blacklist.txt" -Destination "dist\" -Force

          # 压缩dist目录下的所有文件，不包括dist目录本身
          Compress-Archive -Path "dist\*" -DestinationPath "KeywordGacha_DEV.zip" -Force
          
      - name: Delete Previous Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: DEV_BUILD
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.KEYWORDGACGA_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.KEYWORDGACGA_TOKEN }}
        with:
          tag_name: DEV_BUILD
          release_name: KeywordGacha_DEV
          draft: false
          prerelease: false

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.KEYWORDGACGA_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./KeywordGacha_DEV.zip
          asset_name: KeywordGacha_DEV.zip
          asset_content_type: application/octet-stream
